#ifndef CAPRESE_LIBC_INTERNAL_CXX_SYSTEM_ERROR_ERROR_CONDITION_H_
#define CAPRESE_LIBC_INTERNAL_CXX_SYSTEM_ERROR_ERROR_CONDITION_H_

namespace std {
  class error_condition {};
}

#endif // CAPRESE_LIBC_INTERNAL_CXX_SYSTEM_ERROR_ERROR_CONDITION_H_
